# Generated by Django 5.1.4 on 2024-12-15 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubadmin", "0002_child"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group",
                to="clubadmin.group",
            ),
        ),
    ]
